services:
  web:
    container_name: "web"
    ports:
      - 120:8080
    build:
      dockerfile: ./Dockerfile
      context: .
      volumes:
        - ../../../../testtt.csv /code/testtt.csv
        - ../../../../substationsPowesAlti.csv /code/substationsPowesAlti.csv
        - ../../../../power_curves.csv /code/power_curves.csv
      
    

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     # - ./nginx:/etc/nginx/conf.d:rw
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ${/home/ubuntu/neda/ssls/letsencrypt/live/codewithneda.com/fullchain.pem}:/etc/nginx/ssl/codewithneda.crt
  #     - ${/home/ubuntu/neda/ssls/letsencrypt/live/codewithneda.com/privkey.pem}:/etc/nginx/ssl/codewithneda.key
