on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/actions-runner/runner/albanian_wind_analysis/albanian_wind_analysis
          sudo docker-compose up --build -d
